version: "3"
services:
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  node-app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1g
