version: '3'
services:
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
